CI: Skip AdditionalAssets' child comment nodes when creating MS store Application Payload
MS store Application Payload's AdditionalAssets may have child comment
nodes. Then, the Application Payload creation shows error:

Going to create dummy additional assets for Application Payload creation:
MSAppPayload/PDPs/en-us/
Out-File: D:\a\_temp\a99ac4cc-029d-4345-be44-7bf1a3e31d9d.ps1:35
Line |
  35 |    echo NULL > $dummy_assest
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path 'D:\a\endless-key-app\endless-key-app\MSAppPayload\PDPs\en-us\'.

Error: Process completed with exit code 1.

So, skip the nodes if their FileName property are empty.

Fixes: commit 48f16bc64fa9 ("CI: Add additional dummy assets for MS store Application Payload creation")